### ISSUE TITLE
"Error:(143, 25) error: cannot find symbol class StateListener"

### ISSUE THREAD

**Issue by AnthonyUccello** [googlesamples/android-Camera2Video#1]
Greetings

Using Android Studio 0.8.14 I am trying to get this to compile. Right now the gradle build settings incorrectly try to use 'android-l' as the compileSdkVersion. This then tries to download a package that doesn't exist (it was renamed to 20 I believe).

I changed this to 21 but there is an error with the Camera.StateListener (its not found).

Here is my build.gradle 'android' section

android {
    compileSdkVersion 21

```
buildToolsVersion "20.0.0"

sourceSets {
    main {
        dirs.each { dir ->
            java.srcDirs "src/${dir}/java"
            res.srcDirs "src/${dir}/res"
        }
    }
    androidTest.setRoot('tests')
    androidTest.java.srcDirs = ['tests/src']

}
```

I also tried using 20 and build versions as high as 21.1.1 and still couldn't get it to compile (same issue)

**Comment by thagikura** [comment]
Looks this is now fixed.
Closing. Please re-open it if you still see it.
