### ISSUE TITLE
Target Version Android Q Preview

### ISSUE THREAD

**Issue by Xor1980** [googlesamples/android-Camera2Video#100]
With Target SDK Version Android 9.0.99-Q
Stopping video recording after 2-3 seconds from start causing exception saying IllegalStateException every time in Pixel 9. Issue is reproducing every time.
Device details -  
Device Name - Google Pixel
Model Number - Pixel
Android OS Version - 9.0

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
