### ISSUE TITLE
Camera2Video Sample Crashes on Odroid XU4

### ISSUE THREAD

**Issue by bemnet4u** [googlesamples/android-Camera2Video#11]
This sample application crashes when running on Odroid XU4 (http://www.hardkernel.com/main/products/prdt_info.php) running on samsung eynos processor. 

Below is the log. Can someone please help?

12-22 14:13:09.549 2867-10905/? I/MPEG4Writer: setStartTimestampUs: 2867
12-22 14:13:09.549 2867-10905/? I/MPEG4Writer: Earliest track starting time: 2867
12-22 14:13:09.585 2867-10540/? E/libexynosv4l2: failed to ioctl: VIDIOC_QBUF (22 - Invalid argument)
12-22 14:13:09.585 2867-10540/? E/ExynosVideoEncoder: MFC_Encoder_ExtensionEnqueue_Outbuf: Failed to enqueue output buffer
12-22 14:13:09.585 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_DstIn: 2026: Failed - pOutbufOps->Enqueue
12-22 14:13:09.585 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_dstInputBufferProcess: 2285: Failed - DstIn -> event is thrown to client
12-22 14:13:09.586 2867-10540/? E/libexynosv4l2: failed to ioctl: VIDIOC_QBUF (22 - Invalid argument)
12-22 14:13:09.586 2867-10523/? E/ACodec: [OMX.Exynos.AVC.Encoder] ERROR(0x90000006)
12-22 14:13:09.586 2867-10540/? E/ExynosVideoEncoder: MFC_Encoder_ExtensionEnqueue_Outbuf: Failed to enqueue output buffer
12-22 14:13:09.586 2867-10523/? E/ACodec: signalError(omxError 0x90000006, internalError -2147483648)
12-22 14:13:09.586 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_DstIn: 2026: Failed - pOutbufOps->Enqueue
12-22 14:13:09.586 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_dstInputBufferProcess: 2285: Failed - DstIn -> event is thrown to client
12-22 14:13:09.586 2867-10540/? E/libexynosv4l2: failed to ioctl: VIDIOC_QBUF (22 - Invalid argument)
12-22 14:13:09.586 2867-10540/? E/ExynosVideoEncoder: MFC_Encoder_ExtensionEnqueue_Outbuf: Failed to enqueue output buffer
12-22 14:13:09.586 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_DstIn: 2026: Failed - pOutbufOps->Enqueue
12-22 14:13:09.586 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_dstInputBufferProcess: 2285: Failed - DstIn -> event is thrown to client
12-22 14:13:09.586 2867-10540/? E/libexynosv4l2: failed to ioctl: VIDIOC_QBUF (22 - Invalid argument)
12-22 14:13:09.586 2867-10540/? E/ExynosVideoEncoder: MFC_Encoder_ExtensionEnqueue_Outbuf: Failed to enqueue output buffer
12-22 14:13:09.586 2867-10523/? E/ACodec: [OMX.Exynos.AVC.Encoder] ERROR(0x90000006)
12-22 14:13:09.587 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_DstIn: 2026: Failed - pOutbufOps->Enqueue
12-22 14:13:09.587 2867-10523/? E/ACodec: signalError(omxError 0x90000006, internalError -2147483648)
12-22 14:13:09.587 2867-10540/? E/EXYNOS_H264_ENC: Exynos_H264Enc_dstInputBufferProcess: 2285: Failed - DstIn -> event is thrown to client
12-22 14:13:09.587 2867-10523/? E/ACodec: [OMX.Exynos.AVC.Encoder] ERROR(0x90000006)
12-22 14:13:09.587 2867-10523/? E/ACodec: signalError(omxError 0x90000006, internalError -2147483648)
12-22 14:13:09.587 2867-10523/? E/ACodec: [OMX.Exynos.AVC.Encoder] ERROR(0x90000006)
12-22 14:13:09.587 2867-10523/? E/ACodec: signalError(omxError 0x90000006, internalError -2147483648)
12-22 14:13:09.588 2867-10522/? E/MediaCodec: Codec reported err 0x90000006, actionCode 0, while in state 6
12-22 14:13:09.590 2867-10521/? E/MediaCodecSource: Encoder (video) reported error : 0x90000006
12-22 14:13:09.590 2867-10903/? E/MPEG4Writer: The number of recorded samples is 0
12-22 14:13:09.590 2867-10903/? W/MPEG4Writer: 0-duration samples found: 1
12-22 14:13:09.590 2867-10903/? W/MPEG4Writer: 0-duration samples found: 1
12-22 14:13:09.590 2867-10903/? I/MPEG4Writer: Received total/0-length (0/0) buffers and encoded 0 frames. - Video
12-22 14:13:09.592 2867-10522/? E/MediaCodec: Codec reported err 0x90000006, actionCode 0, while in state 0
12-22 14:13:09.592 2867-10522/? E/MediaCodec: Codec reported err 0x90000006, actionCode 0, while in state 0
12-22 14:13:09.592 2867-10522/? E/MediaCodec: Codec reported err 0x90000006, actionCode 0, while in state 0
12-22 14:13:09.593 10472-10472/com.example.android.camera2video I/MediaRecorder.OnError: Media recoreder error = 268435556
12-22 14:13:09.593 2867-10539/? W/libexynosv4l2: failed to ioctl: VIDIOC_DQBUF (22 - Invalid argument)
12-22 14:13:09.596 2867-10523/? W/GraphicBufferSource: Dropped back down to Loaded without Executing
12-22 14:13:09.621 2867-3276/? W/audio_hw_primary: out_write() limiting sleep time 34827 to 23219
12-22 14:13:09.630 2867-3866/? E/BufferQueueProducer: [GraphicBufferSource] dequeueBuffer: BufferQueue has been abandoned
12-22 14:13:09.632 10472-10537/com.example.android.camera2video E/CameraDeviceGLThread-0: Received exception on GL render thread: 
                                                                                          java.lang.IllegalStateException: glDrawArrays: GLES20 error: 0x505
                                                                                              at android.hardware.camera2.legacy.SurfaceTextureRenderer.checkGlError(SurfaceTextureRenderer.java:551)
                                                                                              at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawFrame(SurfaceTextureRenderer.java:346)
                                                                                              at android.hardware.camera2.legacy.SurfaceTextureRenderer.drawIntoSurfaces(SurfaceTextureRenderer.java:740)
                                                                                              at android.hardware.camera2.legacy.GLThreadManager$1.handleMessage(GLThreadManager.java:105)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
12-22 14:13:09.632 10472-10537/com.example.android.camera2video I/CameraDeviceState: Legacy camera service transitioning to state ERROR
12-22 14:13:09.691 2867-3276/? W/audio_hw_primary: out_write() limiting sleep time 34827 to 23219
12-22 14:13:12.256 2867-3276/? W/audio_hw_primary: out_write() limiting sleep time 34827 to 23219
12-22 14:13:15.593 10472-10516/com.example.android.camera2video E/RequestThread-0: Timed out while waiting for request to complete.
12-22 14:13:15.594 10472-10516/com.example.android.camera2video W/CaptureCollector: Preview buffers dropped for request: 0
12-22 14:13:15.594 10472-10516/com.example.android.camera2video E/CameraDeviceState: Cannot receive result while in state: 0
12-22 14:13:15.594 10472-10516/com.example.android.camera2video E/CameraDeviceState: Cannot receive result while in state: 0
12-22 14:13:15.595 10472-10516/com.example.android.camera2video E/CameraDeviceState: Cannot receive result while in state: 0
12-22 14:13:15.609 10472-10493/com.example.android.camera2video E/BufferQueueProducer: [unnamed-10472-1] queueBuffer: BufferQueue has been abandoned
12-22 14:13:15.610 2867-10543/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
12-22 14:13:15.610 2867-2867/? D/CameraHardware: CameraHardware::disableMsgType: 16
12-22 14:13:15.610 2867-3658/? D/CameraHardware: CameraHardware::disableMsgType: 65535
12-22 14:13:15.610 2867-3658/? D/CameraHardware: CameraHardware::stopPreview
12-22 14:13:15.610 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked
12-22 14:13:15.610 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked: stopping PreviewThread
12-22 14:13:15.650 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked: Uninit
12-22 14:13:15.652 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked: StopStreaming
12-22 14:13:15.656 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked: Close
12-22 14:13:15.659 2867-3658/? D/CameraHardware: CameraHardware::stopPreviewLocked: OK
12-22 14:13:15.659 2867-3658/? D/CameraHardware: CameraHardware::cancelPicture
12-22 14:13:15.659 2867-3658/? D/CameraHardware: CameraHardware::releaseCamera
12-22 14:13:15.660 2867-3658/? D/CameraHardware: CameraHardware::setPreviewWindow: preview_stream_ops: 0x0

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
