### ISSUE TITLE
Replace MediaRecorder with MediaCodec

### ISSUE THREAD

**Issue by alexbatashev** [googlesamples/android-Camera2Video#13]
The official documentation says we can use any surface to capture imag (e.g. MediaCodec, MediaRecorder, SurfaceTexture). Anyway, I'm having trouble getting MediaCodec work. Here is my sample code https://github.com/alexbat98/Sample-Camera
Any ideas on how to implement it?

**Comment by qiang-han** [comment]
Your sample code link doesn't work.
https://github.com/alexbat98/Sample-Camera

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
