### ISSUE TITLE
  Applying effects doesn't work in subsequent record sessions

### ISSUE THREAD

**Issue by neilyoung** [googlesamples/android-Camera2Video#16]
If I add this to setUpCaptureRequestBuilder

```
       builder.set(CaptureRequest.CONTROL_EFFECT_MODE,  CameraMetadata.CONTROL_EFFECT_MODE_NEGATIVE);
```

it works the very first recording session. After that the preview (and the recording) is "default"

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
