### ISSUE TITLE
Nexus 5X: Result video is rotated upside down.

### ISSUE THREAD

**Issue by rkostrab** [googlesamples/android-Camera2Video#18]
I ran this sample app on my Nexus 5X device. Preview session is working fine but recorded video is always rotated upside down and the only player I've found which is possible to play video is VLC. 
E.g. built-in Media Viewer says: "Can't play video.".

Please take a look at that.

**Comment by rkostrab** [comment]
I've solved this issue here:
https://github.com/googlesamples/android-Camera2Video/pull/19

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
