### ISSUE TITLE
Square Video Support

### ISSUE THREAD

**Issue by silentsudo** [googlesamples/android-Camera2Video#20]
Add feature to support square video for any resolution.
Developer generally move away to different libraries just because of this simple Square video feature.

**Comment by shanuka** [comment]
+1

**Comment by francismacdougall** [comment]
ashish29agre - what different libraries did you use to get square video?

Has anything happened in regard to an example using these standard components?

**Comment by RamiJ3mli** [comment]
+1

**Comment by RockyLin** [comment]
Square video is a pain in the ass!
Try [Grafika](https://github.com/google/grafika), use OpenGL to transform the image to square.

I'm still working on that. 

PS:Even if it worked on one specific device, it may crash on others... You're Androided!

**Comment by francismacdougall** [comment]
Amazingly enough, I ended up writing my app in javascript for the chrome browser on android, and it starts up the camera in square mode with no problems, and records with it, etc. Basically saves me having to write an app at all!

**Comment by ritesh94** [comment]
:+1:  +1

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
