### ISSUE TITLE
Rendering Problem

### ISSUE THREAD

**Issue by abhinav-adtechs** [googlesamples/android-Camera2Video#22]
Logcat: Couldn't find any suitable preview size - Camera2VideoFragment on a 4.7inch display running 5.1.1
Device config: 16:9 ratio with 720 x 1280 display 
Frame-layout not being rendered along with the screen covering by the app is 80% of the original (approx.)

**Comment by me-azharahmed** [comment]
Logcat: com.example.android.camera2video E/Camera2VideoFragment: Couldn't find any suitable preview size
android-Camera2Video on a 4.7inch Samsung Galaxy S3 device running 5.1.1 (Unofficial)
Device config: (4:3) 8.0 megapixels
While debug I found it is taking video size of 960x720
I have attached screenshots of the Landscape and portrait both modes.
Landscape mode :
![landscape_screenshot_2016-04-18-11-28-33](https://cloud.githubusercontent.com/assets/1615032/14595185/d2c355fe-055a-11e6-8beb-9ccd759fa6ae.png)

Portrait mode :
![portrait_screenshot_2016-04-18-11-28-42](https://cloud.githubusercontent.com/assets/1615032/14595188/e1d0c536-055a-11e6-8112-615449978a02.png)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
