### ISSUE TITLE
Turn off recording, get high framerate preview data?

### ISSUE THREAD

**Issue by twerdster** [googlesamples/android-Camera2Video#26]
Is it possible to turn off the recording and simply receive the camera preview
data at 60fps or 120fps? This would enable real-time processing of the camera stream.

**Comment by cybaker** [comment]
Yes, you can test by with this example by not calling mMediaRecorder.start() in the fragment. You'll get 30 fps with this example, so you'll need to enable high speed previews on a device that supports it.

**Comment by twerdster** [comment]
We tried to do that using a S6 but nothing shows on the screen (although we do see onCaptureCompleted being called at 120 fps). http://pastebin.com/LVdYkWFR
Is there something obviously wrong with what we changed? And more importantly how do we get the pixel data out of either the TotalCaptureResult or the SurfaceTexture? I tried an ImageReader but apparently the ImageReader surface is not a supported surface for the highspeed capture setting.

**Comment by MRYangY** [comment]
@twerdster  Have you reached any conclusions? Can you reach 60 frames in the preview?

**Comment by MRYangY** [comment]
when i use the method createConstrainedHighSpeedCaptureSession occur error below:
Session 1: Failed to create capture session; configuration failed
08-14 15:56:23.058 22882-22882/com.example.android.camera2video W/System.err: android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): endConfigure:442: Camera 0: Error configuring streams: Broken pipe (-32)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
