### ISSUE TITLE
Camera2Video updatePreview() method creates thread but then ignores it?

### ISSUE THREAD

**Issue by RoundSparrow** [googlesamples/android-Camera2Video#27]
I see these 3 lines of code:

```
        HandlerThread thread = new HandlerThread("CameraPreview");
        thread.start();
        mPreviewSession.setRepeatingRequest(mPreviewBuilder.build(), null, mBackgroundHandler);
```

Was the intention to pull that new handler _instead_ of using mBackgroundHandler?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
