### ISSUE TITLE
Unreferenced thread

### ISSUE THREAD

**Issue by jingxizhang** [googlesamples/android-Camera2Video#3]
In Camera2VideoFragment.java line 451 a thread is created and started but not been used.

**Comment by thagikura** [comment]
Leaving it to @yaraki.

@yaraki, could you take a look?

**Comment by thagikura** [comment]
Internal reference: 19358286

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
