### ISSUE TITLE
Front camera ?

### ISSUE THREAD

**Issue by thamer898** [googlesamples/android-Camera2Video#30]
Hello

i need to get the front camera but when i changed this line "  String cameraId = manager.getCameraIdList()[0];" the record button disappear ?

Regards

**Comment by huyquyet** [comment]
In function setUpCameraOutputs(int width, int height){}

You change 
if (facing != null && facing == CameraCharacteristics.LENS_FACING_FRONT) {
                    continue;
                }
=>
if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK) {
                    continue;
                }

**Comment by ferPrieto** [comment]
I got to record with the front camera. Be sure you follow my steps, according to my last post: [(http://stackoverflow.com/a/39309158/2606290)](url)

**Comment by phundal209** [comment]
I fixed this by setting camera id as
cameraId = manager.getCameraIdList()[1];

**Comment by bahiamartins** [comment]
String cameraId = manager.getCameraIdList()[1];

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
