### ISSUE TITLE
IllegalStateException on MediaRecorder.start(Native Method) in Nexus5x

### ISSUE THREAD

**Issue by me-azharahmed** [googlesamples/android-Camera2Video#31]
Device Config:
Name : LG Nexus5x
Android Version : 6.0.1
Kernel : 3.10.73
Root : NO

Facing IllegalStateException just clicking on "Record" button.
able to see the camera preview but when I start the recording it is firing IllegalStateException and crashing the application.

LogCat : 

E/MediaRecorder: start failed: -38
W/System.err: java.lang.IllegalStateException
W/System.err:     at android.media.MediaRecorder.start(Native Method)
W/System.err:     at com.example.aze.interviewmodule.fragments.VideoRecordFragment.startRecordingVideo(VideoRecordFragment.java:696)
W/System.err:     at com.example.aze.interviewmodule.fragments.VideoRecordFragment.onClick(VideoRecordFragment.java:395)
W/System.err:     at android.view.View.performClick(View.java:5204)
W/System.err:     at android.view.View$PerformClick.run(View.java:21155)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:148)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5422)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jeffreyxuworld** [comment]
I encountered the same problem.

**Comment by yudimf** [comment]
I encountered the same problem.

**Comment by naveedahmad99** [comment]
facing same issue on LG Nexus5

**Comment by ejChathuranga** [comment]
won't they fix this?

**Comment by Sharabaddin** [comment]
@ajju4455  @jeffreyxuworld  @yudimf @naveedahmad99 @ejChathuranga 

1 good variant solve : "Found the solution , it appears i had some other service in the background which is using AudioRecord and uses the mic as well.... so thats the -38 :)"

Source: https://stackoverflow.com/a/23975085/4592448

2 variant solve:
"Just found out, that the mic is still block by my activity. Releasing the microfone and the camera fixes the issue."

Source: https://github.com/commonsguy/cwac-cam2/issues/239

**Comment by valterh4ck3r** [comment]
I encountered the same problem.

**Comment by HasanShaikh** [comment]
I am using this to record the video in Karaoke app.
I am using https://github.com/JorenSix/TarsosDSP to get the pitch rate from the microphone.
In this, link it is said that if there is any background service, which uses the microphone then this video recorder will not work.
So when I start recording the video the application crashes in startRecording method.
If I comment the pitch detection code and run, this will record perfectly.
How can I fix this issue now?
this is pitch detection code,

AudioDispatcher dispatcher = AudioDispatcherFactory.fromDefaultMicrophone(22050, 1024, 0);
PitchDetectionHandler pdh = new PitchDetectionHandler() {
@override
public void handlePitch(PitchDetectionResult result, AudioEvent e) {
final float pitchInHz = result.getPitch();
try {
Thread.sleep(200);
} catch (InterruptedException e1) {
e1.printStackTrace();
}
runOnUiThread(new Runnable() {
@override
public void run() {
Log.d("pitchinhz", String.valueOf(pitchInHz));
//TODO: dynamic value
//if (pitchInHz != -1.0)
try {
updatePointerPopupWindow(pitchInHz);
if (isPitchMatches())
Log.d("intersectionval", isPitchMatches() + "");
} catch (Exception e1) {
e1.printStackTrace();
}
}
});
}
};
AudioProcessor p = new PitchProcessor(PitchProcessor.PitchEstimationAlgorithm.FFT_YIN, 22050, 1024, pdh);
dispatcher.addAudioProcessor(p);
new Thread(dispatcher, "Audio Dispatcher").start();

**Comment by tenrakuyu** [comment]
I faced this code -38, my problem is wrong encoder.
On OPPO R9s/Android 7 and Pixel/Android P, the codes below run smoothly:
````
        mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4); // notice here
        mediaRecorder.setOutputFile("/sdcard/" + fileName + ".mp4");
        mediaRecorder.setVideoSize(width, height);
        mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB); // notice here
        mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.MPEG_4_SP); // notice here
````
Yet on VIVO NEXs/Android 8, it will just crash and give me -38, after changed the code as below, the app runs smothly again:
````
        mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP); // notice here
        mediaRecorder.setOutputFile("/sdcard/" + fileName + ".mp4");
        mediaRecorder.setVideoSize(width, height);
        mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264); // notice here
        mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB); // notice here
````

Hope it will help somebody...

**Comment by einsteinarbert** [comment]
Could you get encoder info in device and set into code, some device not
support h264...

**Comment by HBiSoft** [comment]
@einsteinarbert @tenrakuyu  You could set it to default, like this:

    mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT);

But on some devices it will still select h264 even if it should select h263.

I opened a issue on developer.android, you can have a look here and give it a star to get this issue resolved faster - https://issuetracker.google.com/issues/133809182

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
