### ISSUE TITLE
Front-facing camera will darken

### ISSUE THREAD

**Issue by lilincpp** [googlesamples/android-Camera2Video#32]
hi,
i run this sample and no change any code. The Back-Facing camera is normal, but Front-facing camera will darken in the preview. I cant find any question. Any body Can help me?
The Question GIF:
https://github.com/lilincpp/MyCameraDemo/blob/master/camera.gif
![](https://github.com/lilincpp/MyCameraDemo/blob/master/camera.gif)

**Comment by gauravk95** [comment]
Facing same Issue...
Though it happens in some devices like it is darken in Redmi Note 4, but works fine on some other devices...
Tried changing the exposure setting and few other stuff, but no luck...

Please, can anybody help?

**Comment by yadynesh** [comment]
@lilincpp Did you find any solution to this?

**Comment by yadynesh** [comment]
Changing the capture request to TEMPLATE_PREVIEW instead of TEMPLATE_RECORD in startRecording() solves this issue. Not sure how it will affect the video quality though.
`previewBuilder = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_PREVIEW);`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
