### ISSUE TITLE
Recorded Video get cropped from intial previewed area

### ISSUE THREAD

**Issue by deepakjohn141** [googlesamples/android-Camera2Video#34]
At first it shows preview of camera but hen it's starts recording the recodeed size is cropped(smaller) that of the initially previewed area.

**Comment by rudrikpatel** [comment]
I am facing the same issue here.. I am using Galaxy s5. Please let me know if you find any solution.

**Comment by HalseyW** [comment]
Hello,I`m using Mi4 and OnePlus 3T has the same issue.But my Nexus 4 and Nexus 7 are all good.I don`t know why.

**Comment by readysetdev** [comment]
I am also having the same issue using a Google Pixel, has anyone resolved this?

**Comment by mudin3i** [comment]
I have solved this. Try to put 
`builder.set(CaptureRequest.CONTROL_VIDEO_STABILIZATION_MODE,CameraMetadata.CONTROL_VIDEO_STABILIZATION_MODE_OFF);` in `setUpCaptureRequestBuilder`

**Comment by HalseyW** [comment]
I will try your solution. Thanks anyway.




发自网易邮箱大师
On 09/08/2017 17:03, Mudin wrote:

I have solved this. Try to put
builder.set(CaptureRequest.CONTROL_VIDEO_STABILIZATION_MODE,CameraMetadata.CONTROL_VIDEO_STABILIZATION_MODE_OFF); in setUpCaptureRequestBuilder

**Comment by mudin3i** [comment]
I hope it helps :)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
