### ISSUE TITLE
Frame is not changing in samsung s6

### ISSUE THREAD

**Issue by mudin3i** [googlesamples/android-Camera2Video#41]
When I record video using samsung s6, the result's video frame is not changing, only audio is good.

**Comment by pablogeek** [comment]
@Mudin Have you been able to solve this? thanks

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
