### ISSUE TITLE
Front camera recording is not there

### ISSUE THREAD

**Issue by amitd123** [googlesamples/android-Camera2Video#43]
Hi, I am trying to implement video recording and video recording using back camera is working fine using this project but what about front camera. i need to implement video recording using front camera also. Can you explain what should i do?

**Comment by phundal209** [comment]
I fixed this by setting camera id as
cameraId = manager.getCameraIdList()[1];

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
