### ISSUE TITLE
Why use Semaphore ?

### ISSUE THREAD

**Issue by zondaOf2012** [googlesamples/android-Camera2Video#45]
I thought it would do no good.

At least, in the CameraDevice.StateCallback add this: 
```
      @Override
        public void onClosed(@NonNull CameraDevice camera) {
            Log.i("TAG", "CameraDevice.StateCallback onClosed");
            super.onClosed(camera);
            mCameraOpenCloseLock.release();
            mCameraDevice = null;
        }
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
