### ISSUE TITLE
Stretched view

### ISSUE THREAD

**Issue by phundal209** [googlesamples/android-Camera2Video#48]
I am building out a camera feature that doesn't need the frame layout at the bottom with the button. To do so I have removed it out of my code and I get empty white space at the bottom of my view. How can I remove the whitespace and maintain the right aspect ratio?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
