### ISSUE TITLE
Not working in Android Things 0.3

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-Camera2Video#49]
Tried this example on a Raspberry Pi with PiCamera: photos work, video recording (this example) doesn't. Even after disabling the preview which apparently cannot be activated due to lack of hardware support for TextureView.

This is my code: 
[Camera2VideoFragment.java.txt](https://github.com/googlesamples/android-Camera2Video/files/986132/Camera2VideoFragment.java.txt)

Using `mMediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);`
[Logcat_h264.txt](https://github.com/googlesamples/android-Camera2Video/files/986119/Logcat_h264.txt)

Using `mMediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.MPEG_4_SP);`
[Logcat_mpeg_4_sp.txt](https://github.com/googlesamples/android-Camera2Video/files/986125/Logcat_mpeg_4_sp.txt)

Using `setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT);`
[Logcat_default.txt](https://github.com/googlesamples/android-Camera2Video/files/986128/Logcat_default.txt)

**Comment by praveengudhi** [comment]
Hello, are able to live stream using android things on HDMI, i am working on this

**Comment by jonneymendoza** [comment]
having issues too

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
