### ISSUE TITLE
Any plan with cameraview?

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-Camera2Video#51]
Hi I see cameraview in Google's repo, do you have any plan to combine those?
https://github.com/google/cameraview

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
