### ISSUE TITLE
How to flip the recorded video

### ISSUE THREAD

**Issue by prudhvirajkumar10** [googlesamples/android-Camera2Video#54]
I'm recording video through front camera. I just want to flip the video as what it looks like in the preview. Please help me..!!

**Comment by LWChris** [comment]
Easiest way on your PC should be using ffmpeg:

`.\ffmpeg.exe -i original.mp4 -vf "transpose=0,transpose=1" flipped.mp4`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
