### ISSUE TITLE
Bad Video Output

### ISSUE THREAD

**Issue by opannapo** [googlesamples/android-Camera2Video#59]
Can't playing video frames but good on audio result.
Video frames only running after audio playing completed.

To make this sample running fine, i must restart my phone before.
Confused :(

**Comment by pablogeek** [comment]
@opannapo Have you been able to solve this?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
