### ISSUE TITLE
Front-facing camera can't video

### ISSUE THREAD

**Issue by wardenlzr** [googlesamples/android-Camera2Video#60]
The official code changed in the following places

String cameraId = manager.getCameraIdList()[1];

Can't video 
How can I solve?

**Comment by zMrSnow** [comment]
you need find Back CAMERA ID with code like my : 

`
for(String cameraId : cameraManager.getCameraIdList()){
                CameraCharacteristics cameraCharacteristics = cameraManager.getCameraCharacteristics(cameraId);
                if(cameraCharacteristics.get(CameraCharacteristics.LENS_FACING) ==
                        CameraCharacteristics.LENS_FACING_BACK){
                    continue;
                }
mCameraId = cameraId;
return;
}
`

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
