### ISSUE TITLE
Session has been closed; further changes are illegal

### ISSUE THREAD

**Issue by ejChathuranga** [googlesamples/android-Camera2Video#61]
When I'm trying to call again and again `startRecordingVideo()` method, few times it worked and then rise an error that telling `Session has been closed; further changes are illegal`. Directly focused in `updatePreview()` method and script is `            mPreviewSession.setRepeatingRequest(mPreviewBuilder.build(), null, mBackgroundHandler);
`

Where would need to update?
Is this error occurs bcoz is the sessions are not closed simultaneously ?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
