### ISSUE TITLE
Failed to create capture session; configuration failed

### ISSUE THREAD

**Issue by ejChathuranga** [googlesamples/android-Camera2Video#62]
While recording video appear above error in GALAXY GRAND PRIME G530
```

E/CameraDeviceState: Cannot call idle while in state: 0
09-29 11:20:07.895 10796-10796/com.android.ejsoft.video_upload_000web E/CameraCaptureSession: Session 15: Failed to create capture session; configuration failed
```

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
