### ISSUE TITLE
Camera preview freezing after record button clicked

### ISSUE THREAD

**Issue by qadirsuh** [googlesamples/android-Camera2Video#65]
I am testing this code on my Huwai P10 lite.

My video preview is freezing after Record button clicked.

here is the video clip, please see the last part of this clip. On Record Video button I am starting your Camera2VideoActivity (I have changed the buttons for now)
https://youtu.be/pRnoBcjLOmg?t=18s

**Comment by toffii** [comment]
I got the exact same issue. Working fine on other devices including Samsung, Asus, Huawei Honor series.

Still have not been able to figure out a solution.

**Comment by h3clikejava** [comment]
Has anyone solved this problem?

**Comment by ale-getman** [comment]
Has anyone solved this problem? (

**Comment by amspayam** [comment]
I Have the same issue

**Comment by amspayam** [comment]
I changed this line of code    
`mMediaRecorder.setVideoSize(mVideoSize.getWidth(), mVideoSize.getHeight());`
to
`mMediaRecorder.setVideoSize(mPreviewSize.getWidth(), mPreviewSize.getHeight());`
and it worked.

**Comment by qadir-genetech** [comment]
@amspayam I will give this a try. Thanks for sharing this.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
