### ISSUE TITLE
app Crashes on LG device with os version 7.1.1 while starting video recording.

### ISSUE THREAD

**Issue by niketaB** [googlesamples/android-Camera2Video#66]
I am using Camera2Api to record videos.
This example itself is crashing on device LG Q with OS version 7.1.1.
I have tried by removing line to set videoFrameRate.
Then it started to fail with error "IMediaRecorder died."

Please let me know if anyone finds the solution asap.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
