### ISSUE TITLE
Incorrect Video Size Limitation in ChooseVideoSize()?

### ISSUE THREAD

**Issue by dathat** [googlesamples/android-Camera2Video#7]
Function specifies: 
- In this sample, we choose a video size with 3x4 aspect ratio. Also, we don't use sizes larger
- than 1080p, since MediaRecorder cannot handle such a high-resolution video.

Should this: 
"if (size.getWidth() == size.getHeight() \* 4 / 3 && size.getWidth() <= 1080)"

Be this (restrict height to 1080 instead of width)?:
"if (size.getWidth() == size.getHeight() \* 4 / 3 && size.getHeight() <= 1080)"

**Comment by kmturley** [comment]
I thought the same thing, as you want to support HD video. I've tried using:

```
if (size.getWidth() == size.getHeight() * 16 / 9 && size.getHeight() <= 1080) {
```

But then video recorded in landscape mode has green lines all over it, maybe the MediaRecorder can't handle it

**Comment by kmturley** [comment]
I found another issues around:

Camera2VideoFragment.java
line 238

```
if (size.getWidth() == size.getHeight() * 16 / 9 && size.getHeight() <= 1080) {
```

line 264

```
if (option.getHeight() == option.getWidth() * h / w && option.getWidth() <= width && option.getHeight() <= height) {
```

This ensures the camera is recording 16:9 HD video and the preview is also large but not too large that green lines appear on the display

**Comment by amitd123** [comment]
I am having same issue
How to solve that issue

**Comment by DavideP92** [comment]
@kmturley Thank you for your useful comment! I was able to obtain a much higher quality video!!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
