### ISSUE TITLE
Unclear comment about an NPE that could come from an undocumented location

### ISSUE THREAD

**Issue by LouisCAD** [googlesamples/android-Camera2Video#70]
Here is a problem: https://github.com/googlesamples/android-Camera2Video/blob/ac4324a4890a20b99bb7138b031e6c19cc79d190/Application/src/main/java/com/example/android/camera2video/Camera2VideoFragment.java#L457
```
// Currently an NPE is thrown when the Camera2API is used but not supported on the
// device this code runs.
```
Why would an NPE be catched there, and where would it be thrown from? This highly unclear, and borderline misleading. A clarification is needed on this point.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location so we can allow Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
