### ISSUE TITLE
Recording into a single file

### ISSUE THREAD

**Issue by Anmolk22** [googlesamples/android-Camera2Video#72]
If I want to pause and then start recording into the same file. How is that possible. I went through documentation I found media recorder . pause() but this doesnt work on  API's lower then N. So do we record videos and then concat videos into a single file using some kind of muxer.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location so we can allow Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
