### ISSUE TITLE
Preview on custom Layout goes to the left corner

### ISSUE THREAD

**Issue by richardboss** [googlesamples/android-Camera2Video#78]
I am not sure if this is can be reported as an issue. But when creating a custom Layout and trying to preview the camera there it goes to the left corner of the layout. 

It could be because the screen of the Motorola Moto C is smaller and when the layout is also a little smaller it just compresses itself.

If this can be viewed as an issue, then I have a more detailed despriction on StackOverflow : [https://stackoverflow.com/questions/49880717/android-camera2video-preview-issue](https://stackoverflow.com/questions/49880717/android-camera2video-preview-issue)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
