### ISSUE TITLE
Lock screen，unLock screen

### ISSUE THREAD

**Issue by Alvin3225** [googlesamples/android-Camera2Video#79]
Preview ,  lock screen, then unlock screen, it doesn't work anymore.

**Comment by yudikarma** [comment]
hi @Alvin9234  i have same issue. you was solve this issue ? please

**Comment by Alvin3225** [comment]
> hi @Alvin9234 i have same issue. you was solve this issue ? please

not yet,after I raised this question last year，I studied it for a few days and didn't know how
to solve it，Because there was not much time at that time，so I didn't use Camera2.I am sorry that I have not helped you.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
