### ISSUE TITLE
Nexus 5 Android M Preview 3

### ISSUE THREAD

**Issue by wdtaylor** [googlesamples/android-Camera2Video#8]
When recording video on Nexus 5 Android M Preview 3 the video file that results is empty (0 bytes in length).

**Comment by keyboardsurfer** [comment]
Do you still encounter this with the consumer release of Android 6.0?

**Comment by ckovamees** [comment]
I run into this issue with released Android 6.0 and latest Camera2Video on a Nexus 5.

**Comment by vkislicins** [comment]
Seeing the same issue.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
