### ISSUE TITLE
setVideoFrameRate not work for me

### ISSUE THREAD

**Issue by MaSiYuan** [googlesamples/android-Camera2Video#80]
i call the method setVideoFrameRate(60),but the output video file is still 30 Framerate

**Comment by ghost** [comment]
Most producers disable camcorder profile high speed so you can record video high speed when set framerate 60fps, you need to use CameraConstrainedHighSpeedCaptureSession API and check a device supports or no. Open camera is a good open source to learn.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
