### ISSUE TITLE
NPE on StartPreview after stopRecording

### ISSUE THREAD

**Issue by cyph3rcod3r** [googlesamples/android-Camera2Video#81]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.camera2.CaptureRequest$Builder android.hardware.camera2.CameraDevice.createCaptureRequest(int)' on a null object reference
        at camera2.Camera2Fragment.startPreview(Camera2Fragment.java:1093)
        at camera2.Camera2Fragment.stopRecordingVideo(Camera2Fragment.java:1270)

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
