### ISSUE TITLE
Crash after stopping recording

### ISSUE THREAD

**Issue by robinvanPersie** [googlesamples/android-Camera2Video#82]
when i click button to start recording, everything is ok.  but when i click button to stop recording , the app was crashed.

![aaa](https://user-images.githubusercontent.com/10293096/40951504-ee1445e8-68a9-11e8-85df-e33b156750a6.png)

**Comment by robinvanPersie** [comment]
solution is in #46 ,  not #57 。 it's work for me

**Comment by everyOneNo** [comment]
From startPreview(), comment out closePreviewSession();
private void stopRecordingVideo() {
        // UI
        mIsRecordingVideo = false;
        mButtonVideo.setText(R.string.record);
        // Added by Ben Ning, to resolve exception issue when stop recording.
        try {
            mPreviewSession.stopRepeating();
            mPreviewSession.abortCaptures();
        } catch (CameraAccessException e) {
            e.printStackTrace();
        }
        // Stop recording
        mMediaRecorder.stop();
        mMediaRecorder.reset();

        Activity activity = getActivity();
        if (null != activity) {
            Toast.makeText(activity, "Video saved: " + mNextVideoAbsolutePath,
                    Toast.LENGTH_SHORT).show();
            Log.d(TAG, "Video saved: " + mNextVideoAbsolutePath);
        }
        mNextVideoAbsolutePath = null;
        startPreview();
    }

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
