### ISSUE TITLE
Is there an alternate for setting video orientation of the output file?

### ISSUE THREAD

**Issue by shamravu** [googlesamples/android-Camera2Video#83]
This is not an issue but a query.

public void setOrientationHint (int degrees) is the method used by the MediaRecorder API to set the orientation hint for output video playback and this should be called before preparing MediaRecorder object. I want to know if I can set Orientation of the video other than using MediaRecorder.setOrientationHint.

Thanks
Ravi

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
