### ISSUE TITLE
How to add timestamp on each frame?

### ISSUE THREAD

**Issue by anonym24** [googlesamples/android-Camera2Video#85]
How to add timestamp on each frame? Is it possible with CameraCaptureSession?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
