### ISSUE TITLE
Heating during capture

### ISSUE THREAD

**Issue by pkalebu** [googlesamples/android-Camera2Video#88]
Has anyone encountered the problem of overheating to around 50 degrees or above during capture? I measured my temperature using the Snapdragon Profiler, and I noticed the temperature quickly increases when recording is initiated. At times, I see a drop in framerate as a result.

Would anyone know what may be causing this, especially since the CPU isn't being tasked with much.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
