### ISSUE TITLE
Video Pause/Resume...

### ISSUE THREAD

**Issue by ArindamAndroid** [googlesamples/android-Camera2Video#91]
Video pause/resume is not their.

**Comment by ghost** [comment]
From Android 7.0 MediaRecorder supported API

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
