### ISSUE TITLE
the recorded video has a problem, it shows a screenshot that takes a time equal to whole of the video

### ISSUE THREAD

**Issue by fahime-ghasemi** [googlesamples/android-Camera2Video#93]
The recorded video has a problem. It shows a screenshot that takes a time equal to whole of the video. after that time video playing starts. 
I haven't changed anything in the demo app, just see the recorded video that saved.

**Comment by xhanix** [comment]
Are you on Galaxy S7? There is a power issue. Try this:
[Docs: https://developer.android.com/training/scheduling/wakelock]
Wake up the cpu with PowerManager (PARTIAL flag) before starting the capture. Don't forget to release the lock after done recording.

PowerManager powerManager = (PowerManager) getSystemService(POWER_SERVICE);
WakeLock wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
"MyApp::MyWakelockTag");
wakeLock.acquire();

other solutions/work arounds: https://github.com/googlesamples/android-Camera2Video/issues/24

**Comment by einsteinarbert** [comment]
> Are you on Galaxy S7? There is a power issue. Try this:
> [Docs: https://developer.android.com/training/scheduling/wakelock]
> Wake up the cpu with PowerManager (PARTIAL flag) before starting the capture. Don't forget to release the lock after done recording.
> 
> PowerManager powerManager = (PowerManager) getSystemService(POWER_SERVICE);
> WakeLock wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,
> "MyApp::MyWakelockTag");
> wakeLock.acquire();
> 
> other solutions/work arounds: #24

I call it in main activity but no luck, my device: Samsung J7 Pro

**Comment by andreififiita** [comment]
I have the exact same issue.

**Comment by abel-tefera-beez** [comment]
Same issue using GalaxyS7

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
