### ISSUE TITLE
Where is the video file getting stored?

### ISSUE THREAD

**Issue by besonders-santhosh** [googlesamples/android-Camera2Video#94]
Hi I am new to Android. I just set up and ran this in simulator, i want to know where the video is stored?
Can i check in computer or its available only in the emulator phone? Please let me know the path where i can go and play.. 

Also, I tried connecting my Huawei Honor 9N phone through USB...  set developer options and USB debugging modes ON.. , but still i am not able to see my phone available to run this app in my phone.. 
Please suggest. (when i am using the Assistant troubleshoot option, there are 3 steps...
step1:  i can see my phone under "android studio detected following USB devices connected to "
step 2: Enable USB debugging.  (done)
step3: Restart ADB.. done no use.. still

Please help.

**Comment by himeshmyk** [comment]
Hello, you should see the recording in the Android folder of your phone or of the emulator's Android SDK storage.
/storage/Android/data/com.example.camera2video

**Comment by ZhangXinNan** [comment]
I found the recorded video from 'adb shell'
```shell
hero2qltechn:/ $ ls -lh /storage/emulated/0/Android/data/com.example.android.camera2video/files/                                            
total 2.1M
-rw-rw---- 1 u0_a151 sdcard_rw 4.3M 2019-06-10 16:36 **1560155758428.mp4**
```

but I can not find this video by other ways.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
