### ISSUE TITLE
Camera freezes after unlocking the phone after a few minutes.

### ISSUE THREAD

**Issue by yadynesh** [googlesamples/android-Camera2Video#98]
I open my camera and then lock the screen for a few minutes. Now, when I unlock the screen after a few minutes, the camera freezes. This behaviour is random and the time before the camera freezes is also random.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
