### ISSUE TITLE
Rear camera showing solid green color, front camera is fine.

### ISSUE THREAD

**Issue by jay-choudhary91** [googlesamples/android-Camera2Video#99]
No preview is showing when user record video from rear camera. Front camera preview is working fine. although recorded video are fine in both cases.  How can i remove green color preview issue. Thanks in advance.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
